import type { LabColor, RgbColor } from '../palette-types.js';

export type ExtractionAlgorithm = 'lab-kmeans' | 'mmcq';

/**
 * Immutable sample representing a single observed valid pixel in RGB and Lab color spaces.
 */
export interface ExtractionSample {
    readonly rgb: Readonly<RgbColor>;
    readonly lab: Readonly<LabColor>;
}

/**
 * Immutable set of valid image samples supplied to an extraction algorithm.
 */
export interface ExtractionSampleSet {
    readonly samples: readonly ExtractionSample[];
    readonly validPixels: number;
}

/**
 * Observed color candidate generated by an extraction algorithm prior to shared normalization.
 */
export interface ExtractionCandidate {
    readonly rgb: Readonly<RgbColor>;
    readonly lab: Readonly<LabColor>;
    readonly population: number;
    readonly sourceIndex: number;
}

/**
 * Structured diagnostic metadata produced by an extraction algorithm execution.
 */
export type AlgorithmDiagnostics = Readonly<Record<string, unknown>>;

/**
 * Raw candidate result returned by an extraction algorithm to the shared normalizer.
 */
export interface AlgorithmCandidateResult {
    readonly algorithm: ExtractionAlgorithm;
    readonly algorithmVersion: string;
    readonly candidates: readonly ExtractionCandidate[];
    readonly diagnostics: AlgorithmDiagnostics;
}

/**
 * Execution context provided to an extraction algorithm (e.g. cancellation signal).
 */
export interface AlgorithmContext {
    readonly signal?: AbortSignal;
}

/**
 * Generic internal contract for runtime-independent palette extraction algorithms.
 */
export interface NeutralExtractionAlgorithm<Options = unknown> {
    readonly id: ExtractionAlgorithm;
    readonly version: string;
    run(
        input: ExtractionSampleSet,
        options: Readonly<Options>,
        context: Readonly<AlgorithmContext>,
    ): AlgorithmCandidateResult;
}
