import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf-8'));
const version = pkg.version;

if (typeof version !== 'string' || version.length === 0) {
    process.stderr.write(`error: package.json.version is missing or empty\n`);
    process.exit(1);
}

const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[\da-zA-Z.-]+)?(?:\+[\da-zA-Z.-]+)?$/;
if (!SEMVER_RE.test(version)) {
    process.stderr.write(
        `error: package.json.version "${version}" is not valid semver\n`,
    );
    process.exit(1);
}

const outDir = resolve(ROOT, 'src/generated');
mkdirSync(outDir, { recursive: true });

const content = `// Generated by scripts/sync-version.mjs — do not edit manually
export const VERSION = '${version}' as const;
`;

writeFileSync(resolve(outDir, 'version.ts'), content, 'utf-8');
